compressionLevel: mixed

enableGlobalCache: true

plugins:
  - checksum: 627893516485148067c93dbcad672faf71332596b318b10aabf48b7fbdb8d620fedaf1004b922dd08f77c7d0b688a9e6f722d604f2bd22b8196baf2d3d378566
    path: .yarn/plugins/plugin-dedupe-on-install.cjs
    spec: "https://raw.githubusercontent.com/ambar/yarn-plugin-dedupe-on-install/main/index.js"
