on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
  with:
    node-version: '18.x'
- run: yarn install --frozen-lockfile
